USE AdventureWorks2012;
 GO 
 
 SELECT PP.BusinessEntityID,PP.LastName + ' ' + PP.FirstName AS[PERSON NAME],PR.Name AS [μπραβο κουκλακι μου :) :)]
 FROM PERSON.PERSON AS PP
 JOIN SALES.SALESORDERHEADER AS SOH 
 ON SOH.CUSTOMERID=PP.BUSINESSENTITYID
 JOIN SALES.SalesOrderDetail AS SOD
 ON SOH.SalesOrderID=SOD.SalesOrderID
 JOIN PRODUCTION.PRODUCT AS PR
 ON SOD.ProductID = PR.ProductID
 ORDER BY PR.NAME